FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /workspace
COPY .mvn ./.mvn
COPY pom.xml .
COPY src ./src
RUN mvn -s .mvn/settings.xml -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /workspace/target/im-server-0.1.0-SNAPSHOT.jar app.jar
EXPOSE 8080 9000
ENV JAVA_OPTS=""
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
