[general]
static=yes
writeprotect=yes
clearglobalvars=no

[enterprise-im]
exten => u_peer,1,NoOp(Enterprise IM demo media peer)
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => _u_.,1,NoOp(Enterprise IM SIP call to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()
