[global]
type=global
user_agent=EnterpriseIM-Asterisk

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

[endpoint-template](!)
type=endpoint
context=enterprise-im
disallow=all
allow=ulaw,alaw
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

[auth-template](!)
type=auth
auth_type=userpass
password=enterprise-im-sip-secret

[aor-template](!)
type=aor
max_contacts=1
remove_existing=yes

[u_qt](endpoint-template)
auth=u_qt
aors=u_qt

[u_qt](auth-template)
username=u_qt

[u_qt](aor-template)

[u_flutter](endpoint-template)
auth=u_flutter
aors=u_flutter

[u_flutter](auth-template)
username=u_flutter

[u_flutter](aor-template)

[u_web](endpoint-template)
auth=u_web
aors=u_web

[u_web](auth-template)
username=u_web

[u_web](aor-template)

[u_18812345678](endpoint-template)
auth=u_18812345678
aors=u_18812345678

[u_18812345678](auth-template)
username=u_18812345678

[u_18812345678](aor-template)

[u_gateway](endpoint-template)
auth=u_gateway
aors=u_gateway

[u_gateway](auth-template)
username=u_gateway

[u_gateway](aor-template)
